
database:
    adapter: postgresql
    encoding: unicode
    database: dbif164vmi8mle
    port: 5432
    host: ec2-54-225-101-4.compute-1.amazonaws.com
    username: zmahshfwunbaog
    password: EoC9mJSfduUlew9qBG-efLdQq7