database:
    adapter: postgresql
    encoding: unicode
    database: dbevcnaduos7ae
    port: 5432
    host: ec2-54-225-156-230.compute-1.amazonaws.com
    username: gdhwbbgfubhljo
    password: 7y3_GR1HM7_gaPk-G_EJtTdDY8
    timeout: 1500
