database:
    adapter: postgresql
    encoding: unicode
    database: d1jq1q6qhhmije
    port: 5432
    host: ec2-54-83-43-49.compute-1.amazonaws.com
    username: cyajphxxltyppn
    password: 6Qu2coVOwiJfIud3hX_oqnBVqG
    timeout: 1500
