source 'https://rubygems.org'

ruby '2.1.1'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'rest-client', '~> 1.6'
gem 'netrc', '~> 0.7'
gem 'activerecord', '~> 4.1'
gem 'sqlite3', '~> 1.3'
gem 'pg', '0.17.1'

#group :development do
#  gem 'byebug' # replaces 'debugger'
#end
