update skills set synonyms_json='["negotiation","networking","training","team building","corporate communications"]' 
	where key_name='communications';
update skills set synonyms_json='["databases","mysql","sql","analytics","big data","data center"]' 
	where key_name='data_science';
update skills set synonyms_json='["online marketing","marketing","social media","marketing strategy","blogging","seo","lead generation","go-to-market strategy","web analytics", "content strategy","market research","crm","digital media"]'
	where key_name='marketing';
update skills set synonyms_json='["public speaking","thought leadership","powerpoint","community outreach"]' 
	where key_name='presentations';
update skills set synonyms_json='["financial modeling","financial analysis","venture capital","accounting","budgets","fundraising","valuation"]' 
	where key_name='finance';
update skills set synonyms_json='["management","technical leadership","strategy","team leadership","strategic planning","executive management","it strategy"]' 
	where key_name='leadership';
update skills set synonyms_json='["business operations","process improvement","operations management","litigation support","personnel management","six sigma","supply chain management","loss prevention"]' 
	where key_name='ops';
update skills set synonyms_json='["project management","agile project management","program management","change management","agile methodologies", "creative facilitation","event planning"]' 
	where key_name='pmp';
update skills set synonyms_json='["business development","selling","sales operations","pre-sales","sales management","salesforce.com","channel partners","international sales","retail"]' 
	where key_name='sales';
update skills set synonyms_json='["software development","java","ruby on rails","ruby","node.js","c","c#",".net","vb","unix","linux","enterprise software","cloud computing","saas","mobile applications","programming","git"]' 
	where key_name='cs';
update skills set synonyms_json='["user experience","user interface","product management","design","experience design"]' 
	where key_name='ux';
update skills set synonyms_json='["web development","web applications","web design","html","html5","css","javascript","front-end","angularjs","jquery"]' 
	where key_name='web_dev';
