insert into vendors(name, logo_file_name) values('Forbes','vendor_logo_forbes.png');
insert into vendors(name, logo_file_name) values('Inc.','vendor_logo_inc.png');
insert into vendors(name, logo_file_name) values('FastCompany','vendor_logo_fastcompany.png');
insert into vendors(name, logo_file_name) values('Wall Street Journal','vendor_logo_wsj.png');
insert into vendors(name, logo_file_name) values('Harvard Business Review','vendor_logo_hbr.png');
insert into vendors(name, logo_file_name) values('slideshare','vendor_logo_slideshare.png');
insert into vendors(name, logo_file_name) values('Medium','vendor_logo_medium.jpeg');
insert into vendors(name, logo_file_name) values('FirstRound','vendor_logo_firstround.png');
insert into vendors(name, logo_file_name) values('New York Times','vendor_logo_nyt.png');
insert into vendors(name, logo_file_name) values('Quora','vendor_logo_quora.jpeg');
insert into vendors(name, logo_file_name) values('Grovo','vendor_logo_grovo.png');
insert into vendors(name, logo_file_name) values('creativelive','vendor_logo_creativelive.png');
insert into vendors(name, logo_file_name) values('O''Reilly','vendor_logo_oreilly.gif');
insert into vendors(name, logo_file_name) values('GoSkills','vendor_logo_goskills.png');
insert into vendors(name, logo_file_name) values('pluralsight','vendor_logo_pluralsight.png');
insert into vendors(name, logo_file_name) values('TechCrunch','vendor_logo_tc.png');
insert into vendors(name, logo_file_name) values('Jason Calacanis','vendor_logo_jason.jpeg');
insert into vendors(name, logo_file_name) values('Venture Beat','vendor_logo_vb.png');
insert into vendors(name, logo_file_name) values('Business Insider','vendor_logo_bi.png');
insert into vendors(name, logo_file_name) values('Venture Hacks','vendor_logo_vhack.png');