database:
    adapter: postgresql
    encoding: unicode
    database: dortjr9nvmfh3
    port: 5432
    host: ec2-107-21-118-56.compute-1.amazonaws.com
    username: ztkqeuzjboyeit
    password: xxx
    timeout: 1500
